---
:delivery_method: :smtp
:smtp:
    :domain: concord.org
    :user_name: XXXXX
    :password: XXXX
    :address: email-smtp.us-east-1.amazonaws.com
    :port: 587
    :authentication: plain
    :enable_starttls_auto: true